version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    #restart: unless-stopped
    command: yarn run test
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/event-planner
      - NODE_ENV=test
    ports:
      - '3030:3030'
    volumes:
      - '/app/node_modules'
      - '.:/app'
    networks:
      - api-network
    depends_on:
      mongodb:
        condition: service_healthy

  bot:
    build:
      context: bot\.
      dockerfile: Dockerfile
    #restart: unless-stopped
    ports:
      - '8081:8081'
    volumes:
      - '/app/node_modules'
      - '.:/app'
    networks:
      - api-network
    depends_on:
      - api

  frontbot:
    build:
      context: botdemo\.
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - api-network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    restart: always
    networks:
      - api-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/event-planner --quiet

volumes:
  dbdata:

networks:
  api-network:
    driver: bridge