FROM python:3.10-bookworm

WORKDIR /usr/src/app

COPY requirements-dev.txt ./
COPY requirements.txt ./

#RUN python -V
#RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements-dev.txt

RUN pip install --no-cache-dir salesgpt

EXPOSE 8081

COPY . .

CMD [ "python", "run_api.py"]
